# Generated by Django 4.2.7 on 2024-04-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
