# Generated by Django 4.2.7 on 2024-05-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0002_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(default='default.jpg', upload_to='banners'),
        ),
    ]
